export type StoreTier = 'standard' | 'premium'
export type StoreAssetStatus = 'ready' | 'awaiting_coordinates'

export interface IndoorFixedCamera {
  position: [number, number, number]
  target: [number, number, number]
}

export interface StoreCatalogItem {
  id: string
  name: string
  address: string
  coordinates: [number, number]
  poiId?: string
  tier: StoreTier
  signboardModelUrl: string
  exteriorModelUrl?: string
  interiorModelUrl?: string
  canEnter: boolean
  mapScale?: number
  mapRotationY?: number
  fixedIndoorCamera?: IndoorFixedCamera
  enabledOnMap?: boolean
  assetStatus?: StoreAssetStatus
}

const defaultIndoorCamera: IndoorFixedCamera = {
  position: [0, 4.2, 11.5],
  target: [0, 1.8, 0],
}

export const isStoreRenderableOnMap = (item: StoreCatalogItem) => item.enabledOnMap !== false

export const storeCatalog: StoreCatalogItem[] = [
  {
    id: 'seven-eleven-zhongxing',
    name: '7-ELEVEn(中兴通讯大厦店)',
    address: '晨晖路和松涛路交叉口附近',
    coordinates: [121.5873, 31.1983],
    tier: 'premium',
    signboardModelUrl: '/models/store-signboards/seven-eleven-board.glb',
    interiorModelUrl: '/models/store-scenes/seven-eleven-interior.glb',
    canEnter: true,
    mapScale: 1.05,
    fixedIndoorCamera: defaultIndoorCamera,
    assetStatus: 'ready',
  },
  {
    id: 'peets-changtai',
    name: "Peet's Coffee皮爷咖啡(长泰广场店)",
    address: '祖冲之路1239弄6号长泰广场1层05-158室',
    coordinates: [121.6023, 31.2054],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/peets-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'wagas-huizhi',
    name: 'Wagas沃歌斯(汇智国际商业中心店)',
    address: '金科路3057号汇智国际商业中心1栋1层',
    coordinates: [121.6017, 31.203],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/wagas-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'lefit-vanke',
    name: '乐刻运动健身(万科翡翠公园店)',
    address: '荣科路280号2049翡翠公园4楼',
    coordinates: [121.609693, 31.178693],
    poiId: 'B0FFL7CZ6T',
    tier: 'premium',
    signboardModelUrl: '/models/store-signboards/lefit-fitness-board.glb',
    interiorModelUrl: '/models/store-scenes/gym-interior.glb',
    canEnter: true,
    fixedIndoorCamera: {
      position: [0, 5.4, 14],
      target: [0, 2, 0],
    },
    assetStatus: 'ready',
  },
  {
    id: 'sushiexpress-huoli',
    name: '争鲜回转寿司(浦东活力城城市集市店)',
    address: '沪南路2229号复地活力城B1层',
    coordinates: [121.564928, 31.158043],
    poiId: 'B0JR2XJ9WR',
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/sushiexpress-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'coucou-jinke',
    name: '湊湊火锅·茶憩(上海金科路店)',
    address: '金科路3057号汇智国际商业中心L3-7-8',
    coordinates: [121.6019, 31.2033],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/coucou-hotpot-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'jixiang-ziwei',
    name: '吉祥馄饨(上海紫薇店)',
    address: '紫薇路167号',
    coordinates: [121.6157, 31.2022],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/jixiang-wonton-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'heytea-changtai',
    name: '喜茶(长泰广场店)',
    address: '金科路2889号长泰广场1F层',
    coordinates: [121.601, 31.2049],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/heytea-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'naixue-software-park',
    name: '奈雪的茶(浦东软件园店)',
    address: '郭守敬路498号浦东软件园1号楼1层103室',
    coordinates: [121.5985, 31.2101],
    tier: 'premium',
    signboardModelUrl: '/models/store-signboards/naixue-board.glb',
    interiorModelUrl: '/models/store-scenes/naixue-interior.glb',
    canEnter: true,
    fixedIndoorCamera: defaultIndoorCamera,
    assetStatus: 'ready',
  },
  {
    id: 'xiaomi-jinke',
    name: '小米之家(金科路联通厅店)',
    address: '金科路2921号10座104室中国联通',
    coordinates: [121.6008, 31.2055],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/xiaomi-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'zuotingyouyuan-changtai',
    name: '左庭右院鲜牛肉火锅(长泰广场店)',
    address: '祖冲之路1239弄7号地下一层58-33号',
    coordinates: [121.6029, 31.2057],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/zuotingyouyuan-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'muji-changtai',
    name: 'MUJI無印良品(长泰广场店)',
    address: '祖冲之路1239弄2号长泰广场1座',
    coordinates: [121.6016, 31.206],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/muji-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'starbucks-innovation-park',
    name: '星巴克(张江创新园店)',
    address: '科苑路399号10号楼IBM大厦1层109单元',
    coordinates: [121.5912, 31.205],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/starbucks-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'pop-mart-changtai',
    name: 'POP MART泡泡玛特(长泰广场店)',
    address: '金科路2889号长泰广场7座1F-14',
    coordinates: [121.6019, 31.2052],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/pop-mart-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'luckin-zte-s2',
    name: '瑞幸咖啡(中兴通讯S2座大堂店)',
    address: '碧波路889号中兴通讯S2座一层大堂',
    coordinates: [121.585, 31.1977],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/luckin-coffee-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'hema-changtai',
    name: '盒马鲜生(长泰广场店)',
    address: '祖冲之路1239弄7号B1层58-3',
    coordinates: [121.6034, 31.2051],
    tier: 'premium',
    signboardModelUrl: '/models/store-signboards/hema-mr-board.glb',
    exteriorModelUrl: '/models/store-scenes/hema-exterior.glb',
    interiorModelUrl: '/models/store-scenes/hema-mr-interior.glb',
    canEnter: true,
    fixedIndoorCamera: {
      position: [0, 5.6, 13.8],
      target: [0, 1.8, 0],
    },
    assetStatus: 'ready',
  },
  {
    id: 'saizeriya-huizhi',
    name: '萨莉亚意式餐厅(汇智广场店)',
    address: '金科路3057号汇智国际商业中心5楼',
    coordinates: [121.6015, 31.2036],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/saizeriya-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'blue-frog-changtai',
    name: 'Blue Frog蓝蛙(长泰广场店)',
    address: '长泰广场E座1层',
    coordinates: [121.6028, 31.2064],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/blue-frog-exterior.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'mixue-zhangjiang',
    name: '蜜雪冰城(张江店)',
    address: '张江镇科苑路1107-2',
    coordinates: [121.5904, 31.1926],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/mixue-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'mcdonalds-zte',
    name: '麦当劳(浦东张江中兴智慧园)',
    address: '碧波路889号2幢1层09、10室',
    coordinates: [121.5879, 31.1975],
    tier: 'premium',
    signboardModelUrl: '/models/store-signboards/mcdonalds-exterior.glb',
    interiorModelUrl: '/models/store-scenes/mcdonalds-interior.glb',
    canEnter: true,
    fixedIndoorCamera: defaultIndoorCamera,
    assetStatus: 'ready',
  },
  {
    id: 'coooon-haxnbauer',
    name: 'haxnbauer海森堡德国餐厅(长泰广场店)',
    address: '长泰广场店',
    coordinates: [121.600706, 31.206119],
    poiId: 'B0FFIY38B6',
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/coooon-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'gaga-babayiban',
    name: 'gaga(上海第一八佰伴新世纪商厦店)',
    address: '第一八佰伴新世纪商厦店',
    coordinates: [121.516738, 31.227933],
    poiId: 'B0J3FA64QY',
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/gaga-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'golao-guan-jiuliu',
    name: '哥老官重庆美蛙鱼头(九六广场店)',
    address: '九六广场店',
    coordinates: [121.524218, 31.227816],
    poiId: 'B0FFH5GONU',
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/golao-guan-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'island-bookstore-jiuliu',
    name: '上海书城(九六广场店)',
    address: '九六广场店',
    coordinates: [121.524543, 31.227746],
    poiId: 'B0I6JU28HS',
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/island-bookstore-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'yer-shari-dongfang',
    name: '耶里夏丽(东方路店)',
    address: '东方路店',
    coordinates: [121.527373, 31.222905],
    poiId: 'B0FFHK0O6Y',
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/yer-shari-board.glb',
    canEnter: false,
    assetStatus: 'ready',
  },
  {
    id: 'guwu-pending',
    name: '穀屋',
    address: '碧波路690号2号楼',
    coordinates: [121.583275, 31.199925],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/guwu-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
  {
    id: 'latina-brazilian-bbq-pending',
    name: '拉蒂娜巴西烤肉',
    address: '金科路2889号长泰广场东区3座',
    coordinates: [121.602093, 31.206166],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/latina-brazilian-bbq-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
  {
    id: 'moguofang-hotpot-pending',
    name: '魔锅坊火锅',
    address: '祖冲之路2305号天之骄子',
    coordinates: [121.61109, 31.20529],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/moguofang-hotpot-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
  {
    id: 'xiangxiang-sichuan-pending',
    name: '香香川菜',
    address: '紫薇路217号',
    coordinates: [121.616551, 31.203213],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/xiangxiang-sichuan-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
  {
    id: 'xingqinghong-pending',
    name: '兴庆红',
    address: '建中路280号',
    coordinates: [121.612415, 31.201762],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/xingqinghong-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
  {
    id: 'zhangjiang-peninsula-restaurant-pending',
    name: '张江半岛酒楼',
    address: '蔡伦路333号',
    coordinates: [121.623236, 31.199912],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/zhangjiang-peninsula-restaurant-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
  {
    id: 'coco-fresh-tea-pending',
    name: 'CoCo 都可茶饮',
    address: '盛夏路500弄2号101室',
    coordinates: [121.628791, 31.209638],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/coco-fresh-tea-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
  {
    id: 'ic-coffee-pending',
    name: 'IC咖啡',
    address: '张东路1387号21幢203室',
    coordinates: [121.633507, 31.218592],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/ic-coffee-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
  {
    id: 'simply-thai-pending',
    name: 'Simply Thai 天泰',
    address: '金科路2889号长泰广场西区1座',
    coordinates: [121.60827, 31.21142],
    tier: 'standard',
    signboardModelUrl: '/models/store-signboards/simply-thai-board.glb',
    canEnter: false,
    enabledOnMap: true,
    assetStatus: 'ready',
  },
]

export const premiumStoreCatalog = storeCatalog.filter(
  (item) => item.tier === 'premium' && item.canEnter && isStoreRenderableOnMap(item),
)

export const getStoreById = (id: string) => {
  return storeCatalog.find((item) => item.id === id) || null
}
